services:
  postgres:
    image: postgres:16-alpine
    container_name: lms-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lms_platform
    volumes:
      - lms_postgres_data:/var/lib/postgresql/data

volumes:
  lms_postgres_data:
